/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

/**
 *
 * @author juanm
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barca = new javax.swing.JButton();
        athletic = new javax.swing.JButton();
        alaves = new javax.swing.JButton();
        alcorcon = new javax.swing.JButton();
        atMadrid = new javax.swing.JButton();
        albacete = new javax.swing.JButton();
        antequera = new javax.swing.JButton();
        almeria = new javax.swing.JButton();
        arandina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WIKIFUTBOL");
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        barca.setBackground(new java.awt.Color(255, 255, 204));
        barca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barca.png"))); // NOI18N
        barca.setBorder(null);
        barca.setMargin(new java.awt.Insets(30, 30, 30, 30));
        barca.setPreferredSize(new java.awt.Dimension(120, 120));
        barca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcaActionPerformed(evt);
            }
        });
        jPanel1.add(barca);

        athletic.setBackground(new java.awt.Color(255, 255, 204));
        athletic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/athletic.png"))); // NOI18N
        athletic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athleticActionPerformed(evt);
            }
        });
        jPanel1.add(athletic);

        alaves.setBackground(new java.awt.Color(255, 255, 204));
        alaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alaves.png"))); // NOI18N
        alaves.setBorder(null);
        alaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alavesActionPerformed(evt);
            }
        });
        jPanel1.add(alaves);

        alcorcon.setBackground(new java.awt.Color(255, 255, 204));
        alcorcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alcorcon.png"))); // NOI18N
        alcorcon.setBorder(null);
        alcorcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcorconActionPerformed(evt);
            }
        });
        jPanel1.add(alcorcon);

        atMadrid.setBackground(new java.awt.Color(255, 255, 204));
        atMadrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atMadrid.png"))); // NOI18N
        atMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atMadridActionPerformed(evt);
            }
        });
        jPanel1.add(atMadrid);

        albacete.setBackground(new java.awt.Color(255, 255, 204));
        albacete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/albacete.png"))); // NOI18N
        albacete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albaceteActionPerformed(evt);
            }
        });
        jPanel1.add(albacete);

        antequera.setBackground(new java.awt.Color(255, 255, 204));
        antequera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/antequera.png"))); // NOI18N
        antequera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antequeraActionPerformed(evt);
            }
        });
        jPanel1.add(antequera);

        almeria.setBackground(new java.awt.Color(255, 255, 204));
        almeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/almeria.png"))); // NOI18N
        almeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almeriaActionPerformed(evt);
            }
        });
        jPanel1.add(almeria);

        arandina.setBackground(new java.awt.Color(255, 255, 204));
        arandina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arandina.png"))); // NOI18N
        arandina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arandinaActionPerformed(evt);
            }
        });
        jPanel1.add(arandina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcaActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_barcaActionPerformed

    private void alavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alavesActionPerformed
       cambioDeVentanaDatos();
    }//GEN-LAST:event_alavesActionPerformed

    private void alcorconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcorconActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_alcorconActionPerformed

    private void athleticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_athleticActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_athleticActionPerformed

    private void atMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atMadridActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_atMadridActionPerformed

    private void albaceteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albaceteActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_albaceteActionPerformed

    private void antequeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antequeraActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_antequeraActionPerformed

    private void almeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almeriaActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_almeriaActionPerformed

    private void arandinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arandinaActionPerformed
        cambioDeVentanaDatos();
    }//GEN-LAST:event_arandinaActionPerformed

    public void cambioDeVentanaDatos(){
        ventanaDatos nuevaVentana = new ventanaDatos();
        
        nuevaVentana.setVisible(true);
        
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alaves;
    private javax.swing.JButton albacete;
    private javax.swing.JButton alcorcon;
    private javax.swing.JButton almeria;
    private javax.swing.JButton antequera;
    private javax.swing.JButton arandina;
    private javax.swing.JButton atMadrid;
    private javax.swing.JButton athletic;
    private javax.swing.JButton barca;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
